eureka:
  client:
    enabled: false

spring:
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_AUTH_SERVICE_URL:http://auth-service:8080}

